public enum StatusTag
{
    None = 0,
    CounterAttack = 1,
    DamageOverTime = 2,
    HealOverTime = 3,
    WhenHit = 5,
    StartOfTurnTrigger = 7,
    EndOfTurnTrigger = 8,
    WhenDamaged = 9,
    WhenKilled = 10,
    Invulnerable = 11,
    Augment = 12,
    Trap = 13,
    WhenBloodied = 14,
    Stealth = 15,
    OnHpDamageDealt = 16,
    WhenShieldBroken = 17,
    OnClipUsed = 18,
    WhenAllyKilled = 19,
    WhenAfflicted = 20,
    CurrentCardOnly = 21,
    WhenIgnited = 22,
    ResourceGainsPrevented = 23,
}
