public enum StatusTag
{
    None = 0,
    CounterAttack = 1,
    DamageOverTime = 2,
    HealOverTime = 3,
    Vulnerable = 4,
    OnHit = 5,
    AntiHeal = 6,
    StartOfTurnTrigger = 7,
    EndOfTurnTrigger = 8,
    OnDamaged = 9,
    OnDeath = 10,
    Invulnerable = 11,
    Augment = 12,
    Trap = 13,
    OnBloodied = 14,
    Stealth = 15,
    OnHpDamageDealt = 16,
    OnShieldBroken = 17,
    OnClipUsed = 18,
    OnAllyDeath = 19,
    OnAfflicted = 20,
    CurrentCardOnly = 21,
    OnIgnited = 22,
    ResourceGainsPrevented = 23,
}
