public enum ReactionConditionType
{
    OnAttacked = 0,
    OnDamaged = 4,
    OnDamagedHp = 1,
    OnBlinded = 2,
    OnVulnerable = 5,
    OnShieldBroken = 6,
    OnBloodied = 10,
    OnCausedAffliction = 14,
    OnCausedHeal = 15,
    OnCausedStun = 20,
    OnSlay = 21,
    OnDamageDealt = 22,
    OnHpDamageDealt = 23,
    OnAppliedMark = 24,
    OnStealthed = 25,
    OnClipUsed = 27,
    OnTagPlayed = 29,
    OnDodged = 30,
    OnAegised = 31,
    OnNearDeath = 32,
    OnAllyDeath = 33,
    OnAfflicted = 34,
    OnArchetypePlayed = 35,
    OnCardPlayed = 36,
    OnDeath = 99,
}
