public enum ReactionConditionType
{
    OnAttacked = 0,
    OnDamaged = 4,
    OnDamagedHp = 1,
    OnBlinded = 2,
    OnMagicAttacked = 3,
    OnVulnerable = 5,
    OnShieldBroken = 6,
    OnBloodied = 10,
    OnCausedHeal = 15,
    OnCausedStun = 20,
    OnSlay = 21,
    OnDamageDealt = 22,
    OnHpDamageDealt = 23,
    OnClipUsed = 27,
    OnTagPlayed = 29,
    OnDodged = 30,
    OnAegised = 31,
    OnNearDeath = 32,
    OnAllyDeath = 33,
    OnDeath = 99,
}
