public enum ReactionConditionType
{
    WhenAttacked = 0,
    WhenDamaged = 4,
    WhenDamagedHp = 1,
    WhenBlinded = 2,
    WhenVulnerabled = 5,
    WhenShieldBroken = 6,
    WhenBloodied = 10,
    WhenGainedPrimaryResource = 11,
    OnCausedAffliction = 14,
    OnCausedBloodied = 16,
    OnCausedHeal = 15,
    OnCausedStun = 20,
    OnSlay = 21,
    OnDamageDealt = 22,
    OnHpDamageDealt = 23,
    OnAppliedMark = 24,
    OnStealthed = 25,
    OnClipUsed = 27,
    OnTagCardPlayed = 29,
    OnDodged = 30,
    OnAegised = 31,
    WhenNearDeath = 32,
    WhenAllyDeath = 33,
    WhenAfflicted = 34,
    OnArchetypeCardPlayed = 35,
    OnCardPlayed = 36,
    //OnTeamCardCycled = 61, // Need To Implement in #3522 
    WhenKilled = 99,
}
