<script>
  import MegaCorp from "./MegaCorp.svelte";
  import Container from '../Elements/Container.svelte';

  const corps = [
    {corpName: 'Astropoly', desc: "Kings of commerce. If you want to buy or sell, Astropoly has you covered.<br><br>Astropoly are reselling masters who boast the largest selection of cutting-edge merchandise. While most of the other corporations are trying to outcompete each other with corporate espionage, proprietary product innovations, and cutthroat business practices, Astropoly is cutting deals at nice discount margins so they can be the ones selling the latest tech to consumers.<br><br>They are friendly, with the best customer service in the business. On the backend, Astropoly uses robot-staffed warehouses and employs relatively few workers. Astropoly purchase kiosks can be found everywhere in the city, and they offer premier metaverse shopping experiences that are lightyears ahead of their competitors.<br><br>Lest you think they are solely held in positive regard, there are plenty of rumors that Astropoly is involved in reverse engineering, product counterfeiting, privacy invasion, psychological manipulation, and unethical advertising practices. To date, no one has been able to produce sufficient public evidence for any of these claims, so it may just be corporate jealousy..."},

    {corpName: 'Medigeneix', desc: "Gene therapy and body specialists, helping you stimulate, decompress, overperform, relax, and detoxify.<br><br>Medigeneix has taken allopathic medicine into new realms. Not only are they experts at treating disease and performing life-saving surgeries, but they also specialize in all kinds of interventionalist enhancements. They manufacture a broad array of biogenetic augments to improve virtually any physical attribute you want. These are extremely popular for benefactors with highly physical jobs.<br><br>For those who can't afford their augments, cheaper alternatives are available in injectibles and temporary body patches. The effects are brilliant and heralded worldwide, however, there are some known side effects for many of their popular stimulants and enhancers.<br><br>Public image is a bit challenging for Medigeneix since there are often many stories of unethical research methods, engineered treatment deficiencies, chemically addictive additives, and ruthless bill collection practices."},

    {corpName: 'Novoline', desc: "Paramilitary supplier specializing in physical weapons and protection.<br><br>Novoline is a megaconglomerate but most of their well-known business is concentrated in two key lines of business. Novoline is most known for their security services. In a world with no civil police, anyone who wants protection or crime solution services has to pay for it. Many corps outsource their security completely to Novoline, who provide protection via the best-trained augmented military personnel in the region. With any civil governance, Novoline not only delivers security but also criminal investigations and retributions.<br><br>Novoline's other key line of business is the production of kinetic tech weaponry and protection. They have a virtual monopoly on guns, personal protective equipment, and reinforced vehicles of all types. The market dominance might be reasonably warranted since their weapons are consistently rated extremely highly in shooting competitions and consumer surveys.<br><br>In dark and distant fringes of the metroplex, a few rumors circulate about Novoline charging protection money to some businesses and working with shadow crime groups to ensure that there is sufficient demand for their services. Other rumors exist that Novoline's crime solution service sometimes aren't concerned with the facts of an incident and are tainted by their biggest clients' wishes."},

    {corpName: 'Plasmigarchy', desc: "Using plasma to provide power to the world. Holds a virtual monopoly on electricity.<br><br>If you need power or energy systems of any kind, Plasmigarchy has the product you need. Power plants, generators, batteries, chargers, portable energizers are Plasmigarchy's specialties. Most of their power supplies command a purchase premium, although they operate with a very low operating cost, and last for a very long time. Many businesses and consumers cannot afford to purchase Plasmigarchy products right out, so they use amortized financing plans for their energy needs.<br><br>Proponents of Plasmigarchy rave about how eco-sustainable plasma energy is, and how the high energy amplitudes broke through some previous limits in hardware and technology design.<br><br>Detractors of Plasmigarchy claim that the only reason Plasmigarchy is successful in the commercial marketplace is because competing power companies seem to go bankrupt after accidents and sabotage at their power and research facilities. Are these stories true? Maybe so. Maybe not. Either way, in the Metroplex, everyone needs electricity, so it doesn't matter how people feel about this MetroCorp."},
    
    {corpName: 'Secubotics', desc: "The world's premier manufacturer of robotic security devices of all kinds.<br><br>Using Secubotics products, you can fully automate your business security with unstoppable industrial-grade protection robots of all shapes and sizes, available for all environments ranging from urban settings to jungles, or even underwater. Secubotics provides the community with the best in high-tech security, patrol bots, building management systems, cameras, thermal scanners, weapon turrets, and everything else you might need. If you want security high you can rely upon and want to avoid the unpredictable motivations of humans, Secubotics is your ideal choice.<br><br>In addition to their security products, Secubotics are also one of the leading designers of artificial intelligence for all purposes. Replace your human workers with drones. Replace your design team with top-rated AI designers. Integrate highly-trained intelligence models into any product for very affordable integration prices.<br><br>While some of the work of Secubotics is controversial in the public sphere due to varying levels of trust of robots and AI, there are virtually no commonly known rumors of any corporate corruption or major ethical issues."},

    {corpName: 'Tritoonico', desc: "Mystical, secretive, and arcane. A quasi-religious organization that teaches the fundamentals of magic power.<br><br>Tritoonico's ornate temples and hyper-modern hospital buildings are very prominent sights in the Metroplex. Tritoonico hospitals offer treatments at super affordable prices for the poor and needy. They are also the preferred medical destination for some of the very wealthiest and most powerful corporate executives in Metroplex Zero.<br><br>Tritoonico's temples attract followers from all over for daily soul-focus sessions, power readings, and meditations. At the Tritoonico temple stores, they sell all sorts of mystical augments and arcane supplies. Tritoonico's benefactors are extremely passionate, kind, and full of conviction.<br><br>Are they a secular religion? Are they are cult? Are they just self-help profiteers? It's hard to say for sure. While Tritoonico personnel are sickenly polite and nice, there are many, many odds rumors that circulate concerning Tritoonico. Rumors have spread saying they have partaken in human sacrifice and such as part of their spiritual research. There are also many rumors of disappearing persons, which devotees claim happen are the result of ascensions and voluntary monasticism."},

    {corpName: 'ZantoCorp', desc: "Biggest employer of human workers. Specialized in advertising, surveillance, and information channels.<br><br>ZantoCorp is one of the biggest corporations due to their massive employment of human workers. Many wonder what ZantoCorp actually does since they require all employees to sign NDAs, and since they don't have any major products. Despite the amorphous nature of their work, ZantoCorp is extremely popular with many different groups of benefactors. They also seem to be extremely well connected. Their logo seems to show up in just about everything, whether in meatspace or the metaverse.<br><br>While they use some automation and a little bit of AI, ZantoCorp prides itself on being the most human-centric of the modern MetroCorps. They spend the most time cultivating cross-corporate connections, bouncing big business bills, and establishing excellent empathic exchanges of any group in Metroplex.<br><br>Some love ZantoCorp, and others hate them. There are whispers that ZantoCorp might be the most powerful business in Metroplex Zero. However, since no one knows precisely who they are connected with or what they do, there is far more rumor than fact in the collective consciousness."},
    
    {corpName: 'Unaffiliated', desc: "Not affiliated with any MetroCorp, officially.<br><br>While there are significant advantages to strong brand loyalty in Metroplex Zero, there are many people who prefer to appear as unaffiliated as possible. Some are unaffiliated since the corporate lifestyle doesn't really fit with their vision and they would rather live life in Metroplex on their own terms. This includes some people who are personally wealthy or powerful and therefore have less need of corporate assistance. It also includes many people who are very poor or outcasts in society. They can't effectively use any of the benefits offered by corporate employment or brand loyalty.<br><br>There are others, such as freelancers, who use their lack of loyalty as a bargaining tool to cut better deals as they provide unconventional private services to their corporate connections via backchannels. Others remain unaffiliated out of a sense of old-religious or old-moral obligation. They harbor idealistic dreams of revolutionizing Metroplex Zero society and remaking it in a different image.<br><br>Whatever their reasons, everyone who is unaffiliated in Metroplex Zero lives a more challenging and dangerous life."},
  ]
</script>

<Container>
  <h1>MegaCorps of Metroplex Zero</h1>
	{#each corps as corp, i}
    <MegaCorp corpName={corp.corpName} corpDescription={corp.desc} flip={i % 2 === 1}/>
	{/each}
</Container>

<style>
  h1 {
    width: 100%;
    text-align: center;
  }
</style>
